/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;

/**
 *
 * @author sad3y
 */
public class Calculator extends javax.swing.JFrame {
        double firstnum;
        double secondnum;
        double result;
        String operations;
        private Object math;
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdbnDisplay = new javax.swing.JTextField();
        jdbnBackspace = new javax.swing.JButton();
        jdbnSquareRoot = new javax.swing.JButton();
        jdbnClear = new javax.swing.JButton();
        jdbnPlus = new javax.swing.JButton();
        jdbnLog = new javax.swing.JButton();
        jdbnPi = new javax.swing.JButton();
        jdbnSin = new javax.swing.JButton();
        jdbnCos = new javax.swing.JButton();
        jdbnTan = new javax.swing.JButton();
        jdbn7 = new javax.swing.JButton();
        jdbn8 = new javax.swing.JButton();
        jdbn9 = new javax.swing.JButton();
        jdbnMinus = new javax.swing.JButton();
        jdbnMultiply = new javax.swing.JButton();
        jdbn4 = new javax.swing.JButton();
        jdbn5 = new javax.swing.JButton();
        jdbn6 = new javax.swing.JButton();
        jdbnPoint = new javax.swing.JButton();
        jdbnPlusMinus = new javax.swing.JButton();
        jdbn1 = new javax.swing.JButton();
        jdbn2 = new javax.swing.JButton();
        jdbn3 = new javax.swing.JButton();
        jdbn0 = new javax.swing.JButton();
        jdbnEqual = new javax.swing.JButton();
        jdbnBy = new javax.swing.JButton();
        jdbnXpowerY = new javax.swing.JButton();
        jdbnXSquare = new javax.swing.JButton();
        jdbnXCube = new javax.swing.JButton();
        jdbnModulus = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jdbnDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jdbnDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jdbnDisplay.setText("0");
        jdbnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnDisplayActionPerformed(evt);
            }
        });

        jdbnBackspace.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnBackspace.setText("<");
        jdbnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnBackspaceActionPerformed(evt);
            }
        });

        jdbnSquareRoot.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnSquareRoot.setText("√");
        jdbnSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnSquareRootActionPerformed(evt);
            }
        });

        jdbnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jdbnClear.setText("C");
        jdbnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnClearActionPerformed(evt);
            }
        });

        jdbnPlus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jdbnPlus.setText("+");
        jdbnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnPlusActionPerformed(evt);
            }
        });

        jdbnLog.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnLog.setText("log");
        jdbnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnLogActionPerformed(evt);
            }
        });

        jdbnPi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnPi.setText("π");
        jdbnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnPiActionPerformed(evt);
            }
        });

        jdbnSin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnSin.setText("sin");
        jdbnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnSinActionPerformed(evt);
            }
        });

        jdbnCos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnCos.setText("cos");
        jdbnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnCosActionPerformed(evt);
            }
        });

        jdbnTan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnTan.setText("tan");
        jdbnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnTanActionPerformed(evt);
            }
        });

        jdbn7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbn7.setText("7");
        jdbn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbn7ActionPerformed(evt);
            }
        });

        jdbn8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbn8.setText("8");
        jdbn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbn8ActionPerformed(evt);
            }
        });

        jdbn9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbn9.setText("9");
        jdbn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbn9ActionPerformed(evt);
            }
        });

        jdbnMinus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnMinus.setText("-");
        jdbnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnMinusActionPerformed(evt);
            }
        });

        jdbnMultiply.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnMultiply.setText("*");
        jdbnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnMultiplyActionPerformed(evt);
            }
        });

        jdbn4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbn4.setText("4");
        jdbn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbn4ActionPerformed(evt);
            }
        });

        jdbn5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbn5.setText("5");
        jdbn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbn5ActionPerformed(evt);
            }
        });

        jdbn6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbn6.setText("6");
        jdbn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbn6ActionPerformed(evt);
            }
        });

        jdbnPoint.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnPoint.setText(".");
        jdbnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnPointActionPerformed(evt);
            }
        });

        jdbnPlusMinus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnPlusMinus.setText("±");
        jdbnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnPlusMinusActionPerformed(evt);
            }
        });

        jdbn1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbn1.setText("1");
        jdbn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbn1ActionPerformed(evt);
            }
        });

        jdbn2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbn2.setText("2");
        jdbn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbn2ActionPerformed(evt);
            }
        });

        jdbn3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbn3.setText("3");
        jdbn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbn3ActionPerformed(evt);
            }
        });

        jdbn0.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbn0.setText("0");
        jdbn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbn0ActionPerformed(evt);
            }
        });

        jdbnEqual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnEqual.setText("=");
        jdbnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnEqualActionPerformed(evt);
            }
        });

        jdbnBy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnBy.setText("/");
        jdbnBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnByActionPerformed(evt);
            }
        });

        jdbnXpowerY.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnXpowerY.setText("x^y");
        jdbnXpowerY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnXpowerYActionPerformed(evt);
            }
        });

        jdbnXSquare.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnXSquare.setText("x^2");
        jdbnXSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnXSquareActionPerformed(evt);
            }
        });

        jdbnXCube.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnXCube.setText("x^3");
        jdbnXCube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnXCubeActionPerformed(evt);
            }
        });

        jdbnModulus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jdbnModulus.setText("%");
        jdbnModulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnModulusActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jMenuItem1.setText("Standard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        jMenuItem2.setText("Scintific");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jdbnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdbn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdbn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdbn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdbnBackspace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jdbn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jdbnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jdbnPlusMinus, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jdbn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdbnSquareRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jdbn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdbn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdbnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jdbn2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(jdbn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jdbn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdbnPlus, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(jdbnMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdbnMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdbnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdbnBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jdbnLog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                        .addComponent(jdbnPi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jdbnXpowerY)
                                    .addComponent(jdbnXSquare)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jdbnModulus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdbnXCube)
                            .addComponent(jdbnSin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdbnTan, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(jdbnCos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jdbnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jdbnSquareRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                            .addComponent(jdbnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jdbnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jdbnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jdbnModulus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(jdbnXCube, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jdbnMinus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(jdbn9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdbnLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdbnSin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdbn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdbnCos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jdbn8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(jdbn7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jdbn4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jdbn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdbnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jdbnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdbn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdbn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdbn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdbnBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jdbnXpowerY, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jdbnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jdbnPoint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jdbn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jdbnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jdbnEqual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdbnXSquare, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(280, 280, 280))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setResizable(true);
        this.setSize(575, 530);
        jdbnDisplay.setSize(542, 45);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
        this.setSize(400, 530);
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setResizable(true);
        this.setSize(400, 530);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jdbnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnDisplayActionPerformed
        
    }//GEN-LAST:event_jdbnDisplayActionPerformed

    private void jdbnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnClearActionPerformed
        jdbnDisplay.setText("");
    }//GEN-LAST:event_jdbnClearActionPerformed

    private void jdbnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnBackspaceActionPerformed
        String bsp = null;
        
        if(jdbnDisplay.getText().length() > 0)
        {
            StringBuilder strb = new StringBuilder(jdbnDisplay.getText());
            strb.deleteCharAt(jdbnDisplay.getText().length()-1);
            bsp = strb.toString();
            jdbnDisplay.setText(bsp);
        }
    }//GEN-LAST:event_jdbnBackspaceActionPerformed

    private void jdbn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbn7ActionPerformed
        String iNum = jdbnDisplay.getText() + jdbn7.getText();
        jdbnDisplay.setText(iNum);
        
    }//GEN-LAST:event_jdbn7ActionPerformed

    private void jdbn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbn8ActionPerformed
        String iNum = jdbnDisplay.getText() + jdbn8.getText();
        jdbnDisplay.setText(iNum);
    }//GEN-LAST:event_jdbn8ActionPerformed

    private void jdbn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbn9ActionPerformed
        String iNum = jdbnDisplay.getText() + jdbn9.getText();
        jdbnDisplay.setText(iNum);
    }//GEN-LAST:event_jdbn9ActionPerformed

    private void jdbn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbn4ActionPerformed
        String iNum = jdbnDisplay.getText() + jdbn4.getText();
        jdbnDisplay.setText(iNum);
    }//GEN-LAST:event_jdbn4ActionPerformed

    private void jdbn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbn5ActionPerformed
        String iNum = jdbnDisplay.getText() + jdbn5.getText();
        jdbnDisplay.setText(iNum);
    }//GEN-LAST:event_jdbn5ActionPerformed

    private void jdbn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbn6ActionPerformed
        String iNum = jdbnDisplay.getText() + jdbn6.getText();
        jdbnDisplay.setText(iNum);
    }//GEN-LAST:event_jdbn6ActionPerformed

    private void jdbn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbn1ActionPerformed
        String iNum = jdbnDisplay.getText() + jdbn1.getText();
        jdbnDisplay.setText(iNum);
    }//GEN-LAST:event_jdbn1ActionPerformed

    private void jdbn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbn2ActionPerformed
        String iNum = jdbnDisplay.getText() + jdbn2.getText();
        jdbnDisplay.setText(iNum);
    }//GEN-LAST:event_jdbn2ActionPerformed

    private void jdbn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbn3ActionPerformed
        String iNum = jdbnDisplay.getText() + jdbn3.getText();
        jdbnDisplay.setText(iNum);
    }//GEN-LAST:event_jdbn3ActionPerformed

    private void jdbn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbn0ActionPerformed
        String iNum = jdbnDisplay.getText() + jdbn0.getText();
        jdbnDisplay.setText(iNum);
    }//GEN-LAST:event_jdbn0ActionPerformed

    private void jdbnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnPointActionPerformed
        if(!jdbnDisplay.getText().contains("."))
        {
            jdbnDisplay.setText(jdbnDisplay.getText() + jdbnPoint.getText());
        }
    }//GEN-LAST:event_jdbnPointActionPerformed

    private void jdbnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnPlusMinusActionPerformed
        double ops = Double.parseDouble(String.valueOf(jdbnDisplay.getText()));
        ops =ops * (-1);
        jdbnDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jdbnPlusMinusActionPerformed

    private void jdbnSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnSquareRootActionPerformed
        double ops = Double.parseDouble(String.valueOf(jdbnDisplay.getText()));
        ops =Math.sqrt(ops);
        jdbnDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jdbnSquareRootActionPerformed

    private void jdbnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnLogActionPerformed
        double ops = Double.parseDouble(String.valueOf(jdbnDisplay.getText()));
        ops =Math.log(ops);
        jdbnDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jdbnLogActionPerformed

    private void jdbnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnSinActionPerformed
        double ops = Double.parseDouble(String.valueOf(jdbnDisplay.getText()));
        ops =Math.sin(ops);
        jdbnDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jdbnSinActionPerformed

    private void jdbnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnCosActionPerformed
        double ops = Double.parseDouble(String.valueOf(jdbnDisplay.getText()));
        ops =Math.cos(ops);
        jdbnDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jdbnCosActionPerformed

    private void jdbnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnTanActionPerformed
        double ops = Double.parseDouble(String.valueOf(jdbnDisplay.getText()));
        ops =Math.tan(ops);
        jdbnDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jdbnTanActionPerformed

    private void jdbnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnPiActionPerformed
        double ops;
        ops = (3.14159265358979323846264);
        jdbnDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jdbnPiActionPerformed

    private void jdbnXpowerYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnXpowerYActionPerformed
        double ops = Double.parseDouble(String.valueOf(jdbnDisplay.getText()));
        ops =Math.pow(ops, ops);
        jdbnDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jdbnXpowerYActionPerformed

    private void jdbnXSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnXSquareActionPerformed
        double ops = Double.parseDouble(String.valueOf(jdbnDisplay.getText()));
        ops =(ops*ops);
        jdbnDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jdbnXSquareActionPerformed

    private void jdbnXCubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnXCubeActionPerformed
        double ops = Double.parseDouble(String.valueOf(jdbnDisplay.getText()));
        ops =(ops*ops*ops);
        jdbnDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jdbnXCubeActionPerformed

    private void jdbnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnEqualActionPerformed
        String answer;
        secondnum = Double.parseDouble(jdbnDisplay.getText());
        
        if(operations == "+")
        {
            result = firstnum + secondnum;
            answer = String.format("%.2f", result);
            jdbnDisplay.setText(answer);
        }
        
        else if(operations == "-")
        {
            result = firstnum - secondnum;
            answer = String.format("%.2f", result);
            jdbnDisplay.setText(answer);
        }
        
        else if(operations == "*")
        {
            result = firstnum * secondnum;
            answer = String.format("%.2f", result);
            jdbnDisplay.setText(answer);
        }
        
        else if(operations == "/")
        {
            result = firstnum / secondnum;
            answer = String.format("%.2f", result);
            jdbnDisplay.setText(answer);
        }
        
        if(operations == "%")
        {
            result = firstnum % secondnum;
            answer = String.format("%.2f", result);
            jdbnDisplay.setText(answer);
        }
            
    }//GEN-LAST:event_jdbnEqualActionPerformed

    private void jdbnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnPlusActionPerformed
        firstnum = Double.parseDouble(jdbnDisplay.getText());
        jdbnDisplay.setText(null);
        operations = ("+");
    }//GEN-LAST:event_jdbnPlusActionPerformed

    private void jdbnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnMinusActionPerformed
        firstnum = Double.parseDouble(jdbnDisplay.getText());
        jdbnDisplay.setText(null);
        operations = ("-");
    }//GEN-LAST:event_jdbnMinusActionPerformed

    private void jdbnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnMultiplyActionPerformed
        firstnum = Double.parseDouble(jdbnDisplay.getText());
        jdbnDisplay.setText(null);
        operations = ("*");
    }//GEN-LAST:event_jdbnMultiplyActionPerformed

    private void jdbnByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnByActionPerformed
        firstnum = Double.parseDouble(jdbnDisplay.getText());
        jdbnDisplay.setText(null);
        operations = ("/");
    }//GEN-LAST:event_jdbnByActionPerformed

    private void jdbnModulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnModulusActionPerformed
        firstnum = Double.parseDouble(jdbnDisplay.getText());
        jdbnDisplay.setText(null);
        operations = ("%");
    }//GEN-LAST:event_jdbnModulusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton jdbn0;
    private javax.swing.JButton jdbn1;
    private javax.swing.JButton jdbn2;
    private javax.swing.JButton jdbn3;
    private javax.swing.JButton jdbn4;
    private javax.swing.JButton jdbn5;
    private javax.swing.JButton jdbn6;
    private javax.swing.JButton jdbn7;
    private javax.swing.JButton jdbn8;
    private javax.swing.JButton jdbn9;
    private javax.swing.JButton jdbnBackspace;
    private javax.swing.JButton jdbnBy;
    private javax.swing.JButton jdbnClear;
    private javax.swing.JButton jdbnCos;
    private javax.swing.JTextField jdbnDisplay;
    private javax.swing.JButton jdbnEqual;
    private javax.swing.JButton jdbnLog;
    private javax.swing.JButton jdbnMinus;
    private javax.swing.JButton jdbnModulus;
    private javax.swing.JButton jdbnMultiply;
    private javax.swing.JButton jdbnPi;
    private javax.swing.JButton jdbnPlus;
    private javax.swing.JButton jdbnPlusMinus;
    private javax.swing.JButton jdbnPoint;
    private javax.swing.JButton jdbnSin;
    private javax.swing.JButton jdbnSquareRoot;
    private javax.swing.JButton jdbnTan;
    private javax.swing.JButton jdbnXCube;
    private javax.swing.JButton jdbnXSquare;
    private javax.swing.JButton jdbnXpowerY;
    // End of variables declaration//GEN-END:variables
}
